kind: Deployment
apiVersion: apps/v1
metadata:
  name: sleep-infinity
  namespace: emptydir-testing
  labels:
    app: sleep-infinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep-infinity
  template:
    metadata:
      labels:
        app: sleep-infinity
        deployment: sleep-infinity
    spec:
      volumes:
        - name: testdir
          emptyDir:
            sizeLimit: 1Gi
      containers:
        - name: sleep-infinity
          args:
          - /usr/bin/sleep
          - infinity
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools
          resources:    
            requests:
              ephemeral-storage: "500Mi"
            limits:
              ephemeral-storage: "1Gi"
          volumeMounts:
            - name: testdir
              mountPath: /testdir
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always